language: go

go:
  - 1.11
  - 1.11.x
  - master

env:
  - GO111MODULES = on

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - make all
